version: '3.3'
services:
  brevet_api:
    build: .
    command: python3 -u flask_brevets.py
    volumes:
      - .:/app
    ports:
      - 5001:80
    environment:
      - DB_PORT_27017_TCP_ADDR=db
    links:
      - db
  website:
    image: php:apache  
    volumes:
      - ./website:/var/www/html 
    ports:
      - 5002:80  # host:container
    depends_on:
      - brevet_api
  db:
    image: mongo 
